### ISSUE TITLE
Docs about expo updates vs eas updates

### ISSUE THREAD

**Issue by kennethlynne** [jonsamp/test-expo-dev-client-eas-update#1]
Thanks so much for creating this example. A small detail I am still very confused about is about eas vs expo update. We currently rely on expo publish.

I am not sure if a prerequisite for doing this is to migrate to eas updates first?

**Comment by jonsamp** [comment]
What flow are you trying to accomplish?

Right now, with `expo publish` (which we refer to as "classic updates"), you can publish an update and preview it in Expo Go or a development build by going to expo.dev/@username/project-name?channel=channel-name (replacing username, project-name, and channel name with your user-specific values)

This is a nice workflow, since you can publish and immediately share the changes with someone else without re-building. We want to support that with our new service: EAS Update, so I made this repo to show how to do it after running `eas update`, since we don't have the same web UI in place yet.

**Comment by kennethlynne** [comment]
We needed a way to replace that exact flow you mention, but with eas updates instead of expo publish, and we managed by using finding a service to generate QR codes and publishing updates to a branch and targeting a pr channel to that branch
